// Complete list of countries with ISO 3166-1 alpha-2 codes, names, continents, and flag emojis
export interface Country {
  code: string;
  name: string;
  continent: string;
  flag: string;
}

export const continents = ["Africa", "Americas", "Asia", "Europe", "Oceania"] as const;
export type Continent = typeof continents[number];

export const countries: Country[] = [
  // Africa
  { code: "DZ", name: "Algeria", continent: "Africa", flag: "🇩🇿" },
  { code: "AO", name: "Angola", continent: "Africa", flag: "🇦🇴" },
  { code: "BJ", name: "Benin", continent: "Africa", flag: "🇧🇯" },
  { code: "BW", name: "Botswana", continent: "Africa", flag: "🇧🇼" },
  { code: "BF", name: "Burkina Faso", continent: "Africa", flag: "🇧🇫" },
  { code: "BI", name: "Burundi", continent: "Africa", flag: "🇧🇮" },
  { code: "CV", name: "Cabo Verde", continent: "Africa", flag: "🇨🇻" },
  { code: "CM", name: "Cameroon", continent: "Africa", flag: "🇨🇲" },
  { code: "CF", name: "Central African Republic", continent: "Africa", flag: "🇨🇫" },
  { code: "TD", name: "Chad", continent: "Africa", flag: "🇹🇩" },
  { code: "KM", name: "Comoros", continent: "Africa", flag: "🇰🇲" },
  { code: "CG", name: "Congo", continent: "Africa", flag: "🇨🇬" },
  { code: "CD", name: "Congo (DRC)", continent: "Africa", flag: "🇨🇩" },
  { code: "CI", name: "Côte d'Ivoire", continent: "Africa", flag: "🇨🇮" },
  { code: "DJ", name: "Djibouti", continent: "Africa", flag: "🇩🇯" },
  { code: "EG", name: "Egypt", continent: "Africa", flag: "🇪🇬" },
  { code: "GQ", name: "Equatorial Guinea", continent: "Africa", flag: "🇬🇶" },
  { code: "ER", name: "Eritrea", continent: "Africa", flag: "🇪🇷" },
  { code: "SZ", name: "Eswatini", continent: "Africa", flag: "🇸🇿" },
  { code: "ET", name: "Ethiopia", continent: "Africa", flag: "🇪🇹" },
  { code: "GA", name: "Gabon", continent: "Africa", flag: "🇬🇦" },
  { code: "GM", name: "Gambia", continent: "Africa", flag: "🇬🇲" },
  { code: "GH", name: "Ghana", continent: "Africa", flag: "🇬🇭" },
  { code: "GN", name: "Guinea", continent: "Africa", flag: "🇬🇳" },
  { code: "GW", name: "Guinea-Bissau", continent: "Africa", flag: "🇬🇼" },
  { code: "KE", name: "Kenya", continent: "Africa", flag: "🇰🇪" },
  { code: "LS", name: "Lesotho", continent: "Africa", flag: "🇱🇸" },
  { code: "LR", name: "Liberia", continent: "Africa", flag: "🇱🇷" },
  { code: "LY", name: "Libya", continent: "Africa", flag: "🇱🇾" },
  { code: "MG", name: "Madagascar", continent: "Africa", flag: "🇲🇬" },
  { code: "MW", name: "Malawi", continent: "Africa", flag: "🇲🇼" },
  { code: "ML", name: "Mali", continent: "Africa", flag: "🇲🇱" },
  { code: "MR", name: "Mauritania", continent: "Africa", flag: "🇲🇷" },
  { code: "MU", name: "Mauritius", continent: "Africa", flag: "🇲🇺" },
  { code: "MA", name: "Morocco", continent: "Africa", flag: "🇲🇦" },
  { code: "MZ", name: "Mozambique", continent: "Africa", flag: "🇲🇿" },
  { code: "NA", name: "Namibia", continent: "Africa", flag: "🇳🇦" },
  { code: "NE", name: "Niger", continent: "Africa", flag: "🇳🇪" },
  { code: "NG", name: "Nigeria", continent: "Africa", flag: "🇳🇬" },
  { code: "RW", name: "Rwanda", continent: "Africa", flag: "🇷🇼" },
  { code: "ST", name: "São Tomé and Príncipe", continent: "Africa", flag: "🇸🇹" },
  { code: "SN", name: "Senegal", continent: "Africa", flag: "🇸🇳" },
  { code: "SC", name: "Seychelles", continent: "Africa", flag: "🇸🇨" },
  { code: "SL", name: "Sierra Leone", continent: "Africa", flag: "🇸🇱" },
  { code: "SO", name: "Somalia", continent: "Africa", flag: "🇸🇴" },
  { code: "ZA", name: "South Africa", continent: "Africa", flag: "🇿🇦" },
  { code: "SS", name: "South Sudan", continent: "Africa", flag: "🇸🇸" },
  { code: "SD", name: "Sudan", continent: "Africa", flag: "🇸🇩" },
  { code: "TZ", name: "Tanzania", continent: "Africa", flag: "🇹🇿" },
  { code: "TG", name: "Togo", continent: "Africa", flag: "🇹🇬" },
  { code: "TN", name: "Tunisia", continent: "Africa", flag: "🇹🇳" },
  { code: "UG", name: "Uganda", continent: "Africa", flag: "🇺🇬" },
  { code: "ZM", name: "Zambia", continent: "Africa", flag: "🇿🇲" },
  { code: "ZW", name: "Zimbabwe", continent: "Africa", flag: "🇿🇼" },

  // Americas
  { code: "AG", name: "Antigua and Barbuda", continent: "Americas", flag: "🇦🇬" },
  { code: "AR", name: "Argentina", continent: "Americas", flag: "🇦🇷" },
  { code: "BS", name: "Bahamas", continent: "Americas", flag: "🇧🇸" },
  { code: "BB", name: "Barbados", continent: "Americas", flag: "🇧🇧" },
  { code: "BZ", name: "Belize", continent: "Americas", flag: "🇧🇿" },
  { code: "BO", name: "Bolivia", continent: "Americas", flag: "🇧🇴" },
  { code: "BR", name: "Brazil", continent: "Americas", flag: "🇧🇷" },
  { code: "CA", name: "Canada", continent: "Americas", flag: "🇨🇦" },
  { code: "CL", name: "Chile", continent: "Americas", flag: "🇨🇱" },
  { code: "CO", name: "Colombia", continent: "Americas", flag: "🇨🇴" },
  { code: "CR", name: "Costa Rica", continent: "Americas", flag: "🇨🇷" },
  { code: "CU", name: "Cuba", continent: "Americas", flag: "🇨🇺" },
  { code: "DM", name: "Dominica", continent: "Americas", flag: "🇩🇲" },
  { code: "DO", name: "Dominican Republic", continent: "Americas", flag: "🇩🇴" },
  { code: "EC", name: "Ecuador", continent: "Americas", flag: "🇪🇨" },
  { code: "SV", name: "El Salvador", continent: "Americas", flag: "🇸🇻" },
  { code: "GD", name: "Grenada", continent: "Americas", flag: "🇬🇩" },
  { code: "GT", name: "Guatemala", continent: "Americas", flag: "🇬🇹" },
  { code: "GY", name: "Guyana", continent: "Americas", flag: "🇬🇾" },
  { code: "HT", name: "Haiti", continent: "Americas", flag: "🇭🇹" },
  { code: "HN", name: "Honduras", continent: "Americas", flag: "🇭🇳" },
  { code: "JM", name: "Jamaica", continent: "Americas", flag: "🇯🇲" },
  { code: "MX", name: "Mexico", continent: "Americas", flag: "🇲🇽" },
  { code: "NI", name: "Nicaragua", continent: "Americas", flag: "🇳🇮" },
  { code: "PA", name: "Panama", continent: "Americas", flag: "🇵🇦" },
  { code: "PY", name: "Paraguay", continent: "Americas", flag: "🇵🇾" },
  { code: "PE", name: "Peru", continent: "Americas", flag: "🇵🇪" },
  { code: "KN", name: "Saint Kitts and Nevis", continent: "Americas", flag: "🇰🇳" },
  { code: "LC", name: "Saint Lucia", continent: "Americas", flag: "🇱🇨" },
  { code: "VC", name: "Saint Vincent and the Grenadines", continent: "Americas", flag: "🇻🇨" },
  { code: "SR", name: "Suriname", continent: "Americas", flag: "🇸🇷" },
  { code: "TT", name: "Trinidad and Tobago", continent: "Americas", flag: "🇹🇹" },
  { code: "US", name: "United States", continent: "Americas", flag: "🇺🇸" },
  { code: "UY", name: "Uruguay", continent: "Americas", flag: "🇺🇾" },
  { code: "VE", name: "Venezuela", continent: "Americas", flag: "🇻🇪" },

  // Asia
  { code: "AF", name: "Afghanistan", continent: "Asia", flag: "🇦🇫" },
  { code: "AM", name: "Armenia", continent: "Asia", flag: "🇦🇲" },
  { code: "AZ", name: "Azerbaijan", continent: "Asia", flag: "🇦🇿" },
  { code: "BH", name: "Bahrain", continent: "Asia", flag: "🇧🇭" },
  { code: "BD", name: "Bangladesh", continent: "Asia", flag: "🇧🇩" },
  { code: "BT", name: "Bhutan", continent: "Asia", flag: "🇧🇹" },
  { code: "BN", name: "Brunei", continent: "Asia", flag: "🇧🇳" },
  { code: "KH", name: "Cambodia", continent: "Asia", flag: "🇰🇭" },
  { code: "CN", name: "China", continent: "Asia", flag: "🇨🇳" },
  { code: "CY", name: "Cyprus", continent: "Asia", flag: "🇨🇾" },
  { code: "GE", name: "Georgia", continent: "Asia", flag: "🇬🇪" },
  { code: "IN", name: "India", continent: "Asia", flag: "🇮🇳" },
  { code: "ID", name: "Indonesia", continent: "Asia", flag: "🇮🇩" },
  { code: "IR", name: "Iran", continent: "Asia", flag: "🇮🇷" },
  { code: "IQ", name: "Iraq", continent: "Asia", flag: "🇮🇶" },
  { code: "IL", name: "Israel", continent: "Asia", flag: "🇮🇱" },
  { code: "JP", name: "Japan", continent: "Asia", flag: "🇯🇵" },
  { code: "JO", name: "Jordan", continent: "Asia", flag: "🇯🇴" },
  { code: "KZ", name: "Kazakhstan", continent: "Asia", flag: "🇰🇿" },
  { code: "KW", name: "Kuwait", continent: "Asia", flag: "🇰🇼" },
  { code: "KG", name: "Kyrgyzstan", continent: "Asia", flag: "🇰🇬" },
  { code: "LA", name: "Laos", continent: "Asia", flag: "🇱🇦" },
  { code: "LB", name: "Lebanon", continent: "Asia", flag: "🇱🇧" },
  { code: "MY", name: "Malaysia", continent: "Asia", flag: "🇲🇾" },
  { code: "MV", name: "Maldives", continent: "Asia", flag: "🇲🇻" },
  { code: "MN", name: "Mongolia", continent: "Asia", flag: "🇲🇳" },
  { code: "MM", name: "Myanmar", continent: "Asia", flag: "🇲🇲" },
  { code: "NP", name: "Nepal", continent: "Asia", flag: "🇳🇵" },
  { code: "KP", name: "North Korea", continent: "Asia", flag: "🇰🇵" },
  { code: "OM", name: "Oman", continent: "Asia", flag: "🇴🇲" },
  { code: "PK", name: "Pakistan", continent: "Asia", flag: "🇵🇰" },
  { code: "PS", name: "Palestine", continent: "Asia", flag: "🇵🇸" },
  { code: "PH", name: "Philippines", continent: "Asia", flag: "🇵🇭" },
  { code: "QA", name: "Qatar", continent: "Asia", flag: "🇶🇦" },
  { code: "SA", name: "Saudi Arabia", continent: "Asia", flag: "🇸🇦" },
  { code: "SG", name: "Singapore", continent: "Asia", flag: "🇸🇬" },
  { code: "KR", name: "South Korea", continent: "Asia", flag: "🇰🇷" },
  { code: "LK", name: "Sri Lanka", continent: "Asia", flag: "🇱🇰" },
  { code: "SY", name: "Syria", continent: "Asia", flag: "🇸🇾" },
  { code: "TW", name: "Taiwan", continent: "Asia", flag: "🇹🇼" },
  { code: "TJ", name: "Tajikistan", continent: "Asia", flag: "🇹🇯" },
  { code: "TH", name: "Thailand", continent: "Asia", flag: "🇹🇭" },
  { code: "TL", name: "Timor-Leste", continent: "Asia", flag: "🇹🇱" },
  { code: "TR", name: "Turkey", continent: "Asia", flag: "🇹🇷" },
  { code: "TM", name: "Turkmenistan", continent: "Asia", flag: "🇹🇲" },
  { code: "AE", name: "United Arab Emirates", continent: "Asia", flag: "🇦🇪" },
  { code: "UZ", name: "Uzbekistan", continent: "Asia", flag: "🇺🇿" },
  { code: "VN", name: "Vietnam", continent: "Asia", flag: "🇻🇳" },
  { code: "YE", name: "Yemen", continent: "Asia", flag: "🇾🇪" },

  // Europe
  { code: "AL", name: "Albania", continent: "Europe", flag: "🇦🇱" },
  { code: "AD", name: "Andorra", continent: "Europe", flag: "🇦🇩" },
  { code: "AT", name: "Austria", continent: "Europe", flag: "🇦🇹" },
  { code: "BY", name: "Belarus", continent: "Europe", flag: "🇧🇾" },
  { code: "BE", name: "Belgium", continent: "Europe", flag: "🇧🇪" },
  { code: "BA", name: "Bosnia and Herzegovina", continent: "Europe", flag: "🇧🇦" },
  { code: "BG", name: "Bulgaria", continent: "Europe", flag: "🇧🇬" },
  { code: "HR", name: "Croatia", continent: "Europe", flag: "🇭🇷" },
  { code: "CZ", name: "Czechia", continent: "Europe", flag: "🇨🇿" },
  { code: "DK", name: "Denmark", continent: "Europe", flag: "🇩🇰" },
  { code: "EE", name: "Estonia", continent: "Europe", flag: "🇪🇪" },
  { code: "FI", name: "Finland", continent: "Europe", flag: "🇫🇮" },
  { code: "FR", name: "France", continent: "Europe", flag: "🇫🇷" },
  { code: "DE", name: "Germany", continent: "Europe", flag: "🇩🇪" },
  { code: "GR", name: "Greece", continent: "Europe", flag: "🇬🇷" },
  { code: "HU", name: "Hungary", continent: "Europe", flag: "🇭🇺" },
  { code: "IS", name: "Iceland", continent: "Europe", flag: "🇮🇸" },
  { code: "IE", name: "Ireland", continent: "Europe", flag: "🇮🇪" },
  { code: "IT", name: "Italy", continent: "Europe", flag: "🇮🇹" },
  { code: "XK", name: "Kosovo", continent: "Europe", flag: "🇽🇰" },
  { code: "LV", name: "Latvia", continent: "Europe", flag: "🇱🇻" },
  { code: "LI", name: "Liechtenstein", continent: "Europe", flag: "🇱🇮" },
  { code: "LT", name: "Lithuania", continent: "Europe", flag: "🇱🇹" },
  { code: "LU", name: "Luxembourg", continent: "Europe", flag: "🇱🇺" },
  { code: "MT", name: "Malta", continent: "Europe", flag: "🇲🇹" },
  { code: "MD", name: "Moldova", continent: "Europe", flag: "🇲🇩" },
  { code: "MC", name: "Monaco", continent: "Europe", flag: "🇲🇨" },
  { code: "ME", name: "Montenegro", continent: "Europe", flag: "🇲🇪" },
  { code: "NL", name: "Netherlands", continent: "Europe", flag: "🇳🇱" },
  { code: "MK", name: "North Macedonia", continent: "Europe", flag: "🇲🇰" },
  { code: "NO", name: "Norway", continent: "Europe", flag: "🇳🇴" },
  { code: "PL", name: "Poland", continent: "Europe", flag: "🇵🇱" },
  { code: "PT", name: "Portugal", continent: "Europe", flag: "🇵🇹" },
  { code: "RO", name: "Romania", continent: "Europe", flag: "🇷🇴" },
  { code: "RU", name: "Russia", continent: "Europe", flag: "🇷🇺" },
  { code: "SM", name: "San Marino", continent: "Europe", flag: "🇸🇲" },
  { code: "RS", name: "Serbia", continent: "Europe", flag: "🇷🇸" },
  { code: "SK", name: "Slovakia", continent: "Europe", flag: "🇸🇰" },
  { code: "SI", name: "Slovenia", continent: "Europe", flag: "🇸🇮" },
  { code: "ES", name: "Spain", continent: "Europe", flag: "🇪🇸" },
  { code: "SE", name: "Sweden", continent: "Europe", flag: "🇸🇪" },
  { code: "CH", name: "Switzerland", continent: "Europe", flag: "🇨🇭" },
  { code: "UA", name: "Ukraine", continent: "Europe", flag: "🇺🇦" },
  { code: "GB", name: "United Kingdom", continent: "Europe", flag: "🇬🇧" },
  { code: "VA", name: "Vatican City", continent: "Europe", flag: "🇻🇦" },

  // Oceania
  { code: "AU", name: "Australia", continent: "Oceania", flag: "🇦🇺" },
  { code: "FJ", name: "Fiji", continent: "Oceania", flag: "🇫🇯" },
  { code: "KI", name: "Kiribati", continent: "Oceania", flag: "🇰🇮" },
  { code: "MH", name: "Marshall Islands", continent: "Oceania", flag: "🇲🇭" },
  { code: "FM", name: "Micronesia", continent: "Oceania", flag: "🇫🇲" },
  { code: "NR", name: "Nauru", continent: "Oceania", flag: "🇳🇷" },
  { code: "NZ", name: "New Zealand", continent: "Oceania", flag: "🇳🇿" },
  { code: "PW", name: "Palau", continent: "Oceania", flag: "🇵🇼" },
  { code: "PG", name: "Papua New Guinea", continent: "Oceania", flag: "🇵🇬" },
  { code: "WS", name: "Samoa", continent: "Oceania", flag: "🇼🇸" },
  { code: "SB", name: "Solomon Islands", continent: "Oceania", flag: "🇸🇧" },
  { code: "TO", name: "Tonga", continent: "Oceania", flag: "🇹🇴" },
  { code: "TV", name: "Tuvalu", continent: "Oceania", flag: "🇹🇻" },
  { code: "VU", name: "Vanuatu", continent: "Oceania", flag: "🇻🇺" },
];

// Helper function to get country by code
export function getCountryByCode(code: string): Country | undefined {
  return countries.find(c => c.code === code);
}

// Helper function to get countries by continent
export function getCountriesByContinent(continent: Continent): Country[] {
  return countries.filter(c => c.continent === continent);
}

// Countries grouped by continent for dropdown
export const countriesByContinent = continents.reduce((acc, continent) => {
  acc[continent] = getCountriesByContinent(continent);
  return acc;
}, {} as Record<Continent, Country[]>);
